### ISSUE TITLE
Inconsistencies in repo and SOAR

### ISSUE THREAD

**Issue by zdc217** [techservicesillinois/secops-splunk-null-router#49]
We discovered a couple of inconsistencies that we should rectify with this repo. 

+ In the version drop down on SOAR there is a version 4.0.1 of the app. We never tagged or released such a version and should figure out how to remove it. 

+ The CSOC is using version 0.0.0 but we have a 1.0.0 version available on SOAR, as well as various untagged commits in the repo. We should review those commits and see if we can release a newer tag.

**Comment by edthedev** [comment]
We have updated CHANGELOG with this information. 
Recommended course of action is to update to 5.0.0 and never look back.

https://github.com/techservicesillinois/secops-splunk-null-router/blob/main/CHANGELOG.md
